all: bullseye buster stretch

bullseye:
	cd 11-bullseye && $(MAKE)

buster:
	cd 10-buster && $(MAKE)

stretch:
	cd 9-stretch && $(MAKE)

jessie:
	cd 8-jessie && $(MAKE)

wheezy:
	cd 7-wheezy && $(MAKE)


